  version: "3.9"

  services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
      container_name: elasticsearch
      environment:
        - discovery.type=single-node
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - xpack.security.enabled=true
        - xpack.monitoring.collection.enabled=true
        - ELASTIC_PASSWORD=P@ssw0rd
        - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
        - 9200:9200
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
      restart: always
    kibana:
      image: docker.elastic.co/kibana/kibana:7.11.1
      container_name: kibana
      ports:
        - 5601:5601
      environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
        - ELASTICSEARCH_USERNAME=elastic
        - ELASTICSEARCH_PASSWORD=P@ssw0rd
      depends_on:
        - elasticsearch
      restart: always

  volumes:
    elasticsearch-data:
      driver: local